version: '2.1'
services:
    cv:
        build:
            context: cv
            dockerfile: Dockerfile.standalone
        privileged: true
        network_mode: host
        depends_on:
            - "server"
        devices:
            - "/dev:/dev"
    server:
        build:
            context: server
            dockerfile: Dockerfile
        privileged: true
        network_mode: host
